# Generated by Django 6.0.5 on 2026-05-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
