# Generated by Django 6.0.5 on 2026-05-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_agendamento_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='pago',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status_pagamento',
            field=models.CharField(default='Pendente', max_length=30),
        ),
    ]
